#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAnfZrbzi8PXHLo0anbOul7WutR3w2tjTkW6lwqeWih1psyLG0vtX2FthHSb4/LkH0S4sUuBKEd3A615m3JpF3afYRYrDuwkijntNL+orNssdUHESbOqvjKEdw8dCw9RlxkgnEJ5yj+CsIxu/46RCKgFxZsk0ggISgq8g4N4tz09E2QX8bZR7pWcNXpr4ZwTK9TI/OAkW8QeM/cehkXu2MyyRzHRAeGz52kBK4xvuEDuq7JBbhnIS3JUl4dXjTSNciu/kCc8a1redv6lVQf9SlLJj8T501vE80adNoGwbURsVeZG4UvrtutM+QCVRE+Y9CXh5jZoNE9ZjF/YkSKCb05Q== bas@off-sync.com
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvg/J7LVT9Ro4sCK77b4XVkSA9zJYB/HdrEv29RC+BRyWLB1/G92SlnOuCrqNEigDsHoboRfORnRnVu19FiIGSBq8U+oeSUrMJndsdTuuFSesTp/0XPhmM4OFIrBTfv3c1Hhkrf7Bq7T5RY34/iyTawADIJZ4adwPErOZ2sTuk+Dvg2p2QjEUTphhB7KcGkDDqNg0U6NFiQ5IzWpRaL1vmCExfo65qS9iexA2vS631IcTOdH6azLskjJBIqxsir3y/0Dvpk8ANmqWwXpnErF4soFWEuIR0vb/HlAQU5mXnGXuGiT/YPDGpqxyP9eJWOE2mjkVpyYUwsjprCAWycshBQ== jorrit

hostname: {{HOSTNAME}}

write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp
      
      PermitRootLogin no
      AllowUsers core
      PasswordAuthentication no
      ChallengeResponseAuthentication no

coreos:
  etcd:
    name: etcd
    addr: {{PRIVATE_IP}}:4001
    bind-addr: 0.0.0.0
    peer-addr: {{PRIVATE_IP}}:7001
    cluster-active-size: 1
    snapshot: true
  fleet:
    etcd_servers: http://127.0.0.1:4001
    public-ip: {{PRIVATE_IP}}
    metadata: role={{ROLE}}
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: 00-eth0.network
      runtime: true
      content: |
        [Match]
        Name=eth0
        [Network]
        DNS={{PUBLIC_DNS}}
        Address={{PUBLIC_IP}}
        Gateway={{PUBLIC_GW}}
        Address={{PRIVATE_IP}}/{{PRIVATE_NM}}
    - name: flannel.service
      command: start
      content: |
        [Unit]
        After=network-online.target
        Wants=network-online.target
        Description=flannel is an etcd backed overlay network for containers

        [Service]
        Type=notify
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.10.0.0/16"}'
        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
        #ExecStartPre=/usr/bin/test -e /opt/bin/flanneld || /usr/bin/wget -N -P /opt/bin https://www.dropbox.com/s/f6n8zjno6uspqru/flanneld
        ExecStartPre=/usr/bin/chmod +x /opt/bin/flanneld
        ExecStart=/opt/bin/flanneld -etcd-endpoint http://{{ETCD_ENDPOINT}}:4001 -iface {{PRIVATE_IP}}
    - name: docker.service
      command: start
      content: |
        [Unit]
        After=wait-for-flannel.service
        Wants=wait-for-flannel.service
        After=flannel.service
        Wants=flannel.service
        Description=Docker Application Container Engine
        Documentation=http://docs.docker.io

        [Service]
        EnvironmentFile=/run/flannel/subnet.env
        ExecStartPre=/bin/mount --make-rprivate /
        ExecStart=/usr/bin/docker -d --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU} --iptables=false -s=btrfs -H fd://

        [Install]
        WantedBy=multi-user.target
    - name: confd.service
      command: start
      content: |
        [Unit]
        After=network-online.target
        Wants=network-online.target
        Description=Etcd backed configuration daemon
        
        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
        ExecStartPre=/usr/bin/mkdir -p /etc/confd/conf.d
        ExecStartPre=/usr/bin/mkdir -p /etc/confd/templates
        #ExecStartPre=/usr/bin/test -e /opt/bin/confd || /usr/bin/wget -N -P /opt/bin https://www.dropbox.com/s/gsgjnn2g2n7vaol/confd
        ExecStartPre=/usr/bin/chmod +x /opt/bin/confd
        ExecStart=/opt/bin/confd -node=http://{{ETCD_ENDPOINT}}:4001 -interval=10
  update:
    group: stable
    reboot-strategy: off
